server:
    port: 8019
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ShopAppAngular?useSSL=false&serverTimezone=UTC
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none #là khi ta chạy ánh xạ model sẽ không sinh bảng trong csdl như e-comer
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
        max-file-size: 10MB
        max-request-size: 10MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
api:
    prefix: api/v1
jwt: #Jsonwebtoken
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  secretKey:
